name: Build & Publish

on:
  push:
    branches: [ master, main ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ master, main ]
    paths-ignore:
      - '**/README.md'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@main
      with:
        path: packages/<yourpackage>
    - run: npm install
    - run: npm run build --if-present

    - name: Deploy to demo branch 🚀
      if: github.event_name != 'pull_request'
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        branch: demo
        folder: dist/ClickHousePlay
        
    - name: ZIP Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: '${{steps.package-version.outputs.current-version}}.zip'
        directory: 'dist/ClickHousePlay'
        
    - name: Get Timestamp
      if: github.event_name != 'pull_request'
      id: time
      uses: nanzm/get-time-action@v1.1
      with:
        timeZone: 0
        format: 'YYYYMMDDHHmmss'
        
    - name: Upload release
      if: github.event_name != 'pull_request'
      uses: boxpositron/upload-multiple-releases@1.0.7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_config: |
            release.zip
        release_name: chmate_${{ steps.package-version.outputs.current-version}}_${{ steps.time.outputs.time }}
        tag_name: ${{ steps.time.outputs.time }}
        draft: false
        prerelease: false
        overwrite: true
